### ISSUE TITLE
Extension Making the quick settting looks weird!! 

### ISSUE THREAD

**Issue by ibrahim0891** [qwreey/quick-settings-tweaks#138]
Hi there, 
I just have installed GNOME 46 and having this following error. Extension is working. But it make my quick setting looks weired.

Here is the error-

![Screenshot from 2024-05-02 18-46-34](https://github.com/qwreey/quick-settings-tweaks/assets/106436211/46124f20-f4c8-4aac-922d-ea6365cf3d8b)

Here how it looks like now-

![Screenshot from 2024-05-02 18-49-22](https://github.com/qwreey/quick-settings-tweaks/assets/106436211/3aea590c-8883-4158-95a9-9980058c0f3d)

It is genarelly looks compact and cute , but now it is looking very bulky. I dont have installed any shell theme. It is causing for this extension proble,
Please , check this error. Hope it would be fixed soon. Waiting for an update.
Thanks for making this awesome extension.

**Comment by KruASe76** [comment]
same here
quick settings are now stretched to a half-screen size lol
![Снимок экрана от 2024-05-04 14-25-17](https://github.com/qwreey/quick-settings-tweaks/assets/55000336/19a43fad-bb4e-4564-a449-08cb96b7a42c)

extension version: 26
refuses to load after an update and probably causes visual bugs because it was not properly unloaded

**Comment by qwreey** [comment]
The 'actor-add' error was fixed in version 26.
@KruASe76 Can I see the logs about qst (by `journalctl /bin/gnome-shell --reverse`)

**Comment by KruASe76** [comment]
> The 'actor-add' error was fixed in version 26. @KruASe76 Can I see the logs about qst (by `journalctl /bin/gnome-shell --reverse`)

received an update, now works fine
thanks :)

**Comment by ibrahim0891** [comment]
Thank you so much.  Mine issue is also fixed and its working like a charm!!

**Comment by KruASe76** [comment]
here is the stacktrace anyway if anyone needs:

```
Extension quick-settings-tweaks@qwreey: Error: No signal 'child-added' on object 'StWidget'
Stack trace:
enable@file:///home/kruase/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/extension.js:70:55
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:253:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:461:32
async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:759:24
async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:765:48
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:800:20
async*init@resource:///org/gnome/shell/ui/extensionSystem.js:72:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
start@resource:///org/gnome/shell/ui/main.js:176:11
@resource:///org/gnome/shell/ui/init.js:12:47
@resource:///org/gnome/shell/ui/init.js:21:20
```
