### ISSUE TITLE
GNOME 47 quick settings notifications have bigger buttons than what they're supposed to

### ISSUE THREAD

**Issue by Milli189** [qwreey/quick-settings-tweaks#154]
So I've updated the metadata of the exstension to get it working on gnome 47.

The issue is that when I have the exstension disabled the notifications look like this:

![Screenshot From 2024-09-20 14-34-57](https://github.com/user-attachments/assets/85d502d9-cfa6-48df-b686-525c2731c0b8)

And when I enable the exstension the notifications look like this:

![Screenshot From 2024-09-20 14-35-42](https://github.com/user-attachments/assets/4a3ac69a-a0b3-4fb5-8535-16a6a5ebe283)

As you can see the notifications when the estension is turned on have huge buttons in the quick settings, and they don't have the same size as the one in the first picture when the exstension is disabled.

**Comment by qwreey** [comment]
https://github.com/qwreey/quick-settings-tweaks/issues/148#issuecomment-2375992371

Fixed in dev branch. closing issue
![image](https://github.com/user-attachments/assets/bfc11f0d-50d9-4938-bc75-25b396003964)
