### ISSUE TITLE
Incompatible with Dash to Panel

### ISSUE THREAD

**Issue by DarkMicro** [qwreey/quick-settings-tweaks#155]
Sadly, this Extension does nothing if [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel) is active. I would be grateful if you could look into it and make it work.

**Comment by qwreey** [comment]
지금은 계획이 없습니다. 이는 dash to panel 이 먼저 로드될지, qst 가 먼저 로드될지 모르기 때문에, 익스텐션 로드 이벤트를 기다리고, 이전에 익스텐션이 활성화 되었는지 확인해야합니다.

dash to panel 이 만드는 quick settings 버튼은 그놈과 별도의 것입니다. 그놈이 해당하는 부분을 생성하는것이 아니라 dash to panel 이 이를 생성합니다.

dash to panel 은 모니터의 변경, 설정의 변경에 따라서 이를 유동적으로 생성하거나 지웁니다. 이 모든것을 qst 가 확인하고 처리할 수 있는지는 의문입니다.

처리할 수 있다고 하더라도, 부가효과가 너무 많을 수 있습니다. 따라서 이러한 외부 익스텐션에 대한 허용은 아직 생각이 없습니다.

또한 이는 qst 에서 처리하기 보다, dash to panel 에서 처리하여야 합니다. caffeine 과 같은 익스텐션을 확인하세요, 이 또한 dash to panel 이 생성한 quick settings 에 토글을 추가하지 않습니다. 즉 다른 모든 익스텐션도 dash to panel 의 quick settings 를 변경하지 않습니다.

![image](https://github.com/user-attachments/assets/a389c740-87fd-4c0c-8232-5e814abe5bb9)
![image](https://github.com/user-attachments/assets/cafcc1ab-8a9e-4f1b-9c16-d7c46fa381dc)

따라서 dash to panel 쪽에서, dash to panel 이 생성한 버튼이 그놈이 생성한 메뉴를 열도록 만들어야할 것입니다.

DLDR : Won't fix - we can't fix
