### ISSUE TITLE
Notifications not showing as a separate panel .

### ISSUE THREAD

**Issue by Zetta1Reid0** [qwreey/quick-settings-tweaks#88]
![Снимка на екрана на 2023-05-05 19-52-37](https://user-images.githubusercontent.com/79805086/236519895-b31129ad-2b70-4e5c-834b-9cb396e990de.png)

Last working version is 1.15 .
Distro : Manjaro .
Gnome Shell >= 43.4

**Comment by itsjustarumour** [comment]
Same here.  It was working, now it's not.

Ubuntu 23.04
GNOME 44.0
